cabal-version:      3.4
name:               parlor-game
version:            0.1.0.0
-- synopsis:
-- description:
license:            BSD-3-Clause
license-file:       LICENSE
author:             rmgaray
maintainer:         ramiro.sgaray@gmail.com
-- copyright:
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall

common lang
    default-language: GHC2021
    default-extensions:
        DerivingStrategies
        DerivingVia
        TypeFamilies
        BlockArguments
        LambdaCase
    build-depends:    , base >=4.18 && < 5

library
    import:           warnings, lang
    exposed-modules:  ParlorGame
    -- other-modules:
    -- other-extensions:
    build-depends:    base ^>=4.18.3.0
                      , typedKanren ^>=0.1.0.0
                      , prettyprinter ^>=1.7.1
                      , lens ^>= 5.3.5
    hs-source-dirs:   src
    default-language: GHC2021

